all:
	magic -T gf180mcuC -dnull -noconsole < lef.tcl |grep -v Reading
	magic -T gf180mcuC -dnull -noconsole < mag.tcl |grep -v Reading
	cp gf180_teststructures_flat.mag ../mag/gf180_teststructures.mag

